## makeCacheMatrix caches an inputMatrix and returns a list that consits of several functions. These allow to reset the cached matrix,
## to set an inversed matrix, to get the matrix, to get the inversed matrix, to get the date of change of the matrix and the date of creation of the inversed matrix.
## The function cacheSolve then takes a list generated by makeCacheMatrix and use its functions to return the inverse of the matrix and to cache the up-to-date 
## inversed matrix to makeCacheMatrix

## makeCacheMatrix saves/caches input-matrix and returns 
## list with functions that can be used to set a new matrix, set an inversed matrix and to check
## the date of last changes to the matrix and last creation of the inversed matrix
## written by Simon Gengler on 26/04/2014        

makeCacheMatrix <- function(inputMatrix = numeric()) {        
        
        inverseMatrix <- NULL # stores inverted matrix
        lastChange <- date()    # stores date of last changes to matrix
        dateInversion <- NULL # stores date of last inversion of input-matrix
        
        setMatrix <- function(y){
                inputMatrix <<- y  # input-matrix of environment is set to function argument y
                inverseMatrix <<- NULL # since inverse-matrix has not been computed, it's set to NULL
                lastChange <<- date() # last-change of environment is set to date of now
                dateInversion <<- NULL # date-inversion of environment is set to null since no inverse-matrix computed              
                NULL # nothing is returned since it is a setter function that sets variables in the environment
        }
        
        setInverseMatrix <- function(imatrix) 
        {       dateInversion <<- date() # date-inversion of environment is set to date of now  
                inverseMatrix <<- imatrix # inverse-matrix of environment is set to imatrix  
                NULL # nothing is returned since it is a setter function that sets variables in the environment
        }        
        
        
        getMatrix <- function() inputMatrix # returns value of input-matrix
        getInverseMatrix <- function() inverseMatrix # returns value of inverse-matrix
        getLastChange <- function() lastChange # returns date of last change to matrix
        getInversionDate <- function() dateInversion # returns date of matrix-inversion
        
        
        list(setMatrix = setMatrix, setInverseMatrix = setInverseMatrix, getMatrix = getMatrix,  getInverseMatrix =  getInverseMatrix, getLastChange = getLastChange, getInversionDate = getInversionDate )
        
}


## cacheSolve returns inversed matrix of the matrix cached with makeCacheMatrix, if Matrix is invertable, otherwise returns NULL       
## written by Simon Gengler on 26/04/2014

cacheSolve <- function(smatrix, ...){
        
        # smatrix == list returned from makeCacheMatrix()       
        
        if((is.null(smatrix$getInverseMatrix())) || ( (!is.null(smatrix$getInverseMatrix())) && (smatrix$getLastChange() > smatrix$getInversionDate())))
                
                # if-clause checks if inverse-matrix has already been calculated and if yes, if the last-change to the matirx has been done before the calculation
                # of the inverse-matrix. If inverseMatrix has not been calculated or matrix has been changed after creation of the inversed matrix,
                # the inverseMatrix is calculated via the solve-function and cached using the setInverseMatrix-function of the smatrix-Object
                
        { if(det(smatrix$getMatrix()) == 0){
                # checks if singular matrix, if yes returns NULL
                message("matrix is singular, thus not invertable !" ) 
                return(NULL) }
          else{                    
                  invMatrix <- solve(smatrix$getMatrix(), ...) # computes inverse matrix using solve
                  smatrix$setInverseMatrix(invMatrix)          # set cached inverse matrix of smatrix-object to invMatrix
         }
        }
        
        smatrix$getInverseMatrix()  
        # returns inversed matrix via the getInverseMatrix-function of the smatrix-Object
}




